---

- name: Install postfix
  yum: name=postfix state=latest

- name: Install dovecot and deps
  yum: name={{item}} state=latest
  with_items:
          - dovecot
          - dovecot-mysql
          - dovecot-pigeonhole

- name: Install nginx
  yum: name=nginx state=latest

- name: Install mariadb
  yum: enablerepo=mariadb name={{item}} state=latest
  with_items:
          - MariaDB-client
          - MariaDB-server
          
- name: Install MySQLdb Python package for secure installations.
  yum: name=MySQL-python state=present
          
- name: install php-fpm and its deps
  yum: name={{item}} state=latest
  with_items:
          - php72-php-fpm
          - php72-php-opcache 
          - php72-php-gd
          - php72-php-mysql 
          - php72-php-mcrypt
          - php72-php-cli
          - php72-php-pear
          - php72-php-devel
          - php72-php-pecl-ssh2
          - php72-php-pdo

